typography_spectrum: 1
color:
  brandColors:
    - '#f1f1f1'
    - '#ac1f28'
    - '#585a59'
    - '#e3c9c7'
    - '#dba6a8'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.38164
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd77a901-ad96-4b15-8257-0bdb8656cdbe.png
name: Tribe Conference 2016
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
navigation:
  - id: >-
      https://www.universe.com/events/tribe-conference-2016-tickets-franklin-HL2FYP
    url: >-
      https://www.universe.com/events/tribe-conference-2016-tickets-franklin-HL2FYP
    name: Get Your Tickets Now
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/374ddc06-e7d8-439a-a500-3d3ffe15fdbd.png
collections:
  - filter:
      notType:
        type: WebPage
    index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
  - filter:
      type:
        type: Article
    permalink:
      path: '/:title/'
  - filter:
      type:
        type: WebPage
    permalink:
      path: '/:title/'
      navigable: true
purpose:
  - name: follow
    url: null
    item: 3646ec0f-28ea-4d62-937f-fe4eb0146eb7
