name: TheTribe
favicon: null
layout_spectrum: 1
typography_spectrum: 1
collections:
  - filter:
      notType:
        type: WebPage
    index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
  - filter:
      type:
        type: Article
    permalink:
      path: '/:title/'
  - filter:
      type:
        type: WebPage
    permalink:
      path: '/:title/'
      navigable: true
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#aa222d'
    - '#c9898f'
    - '#595959'
    - '#b85b68'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose:
  - name: follow
    url: null
    item: 3646ec0f-28ea-4d62-937f-fe4eb0146eb7
