typography_spectrum: 1
color:
  brandColors:
    - '#f1f1f1'
    - '#ac1f28'
    - '#585a59'
    - '#e3c9c7'
    - '#dba6a8'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.38164
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f8621f87-4baf-4c82-9459-7d6914701930.png
name: TheTribe
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/76e094d8-805f-4bd9-8d21-eb5f618896f1.png
collections:
  - filter:
      notType:
        type: WebPage
    index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
  - filter:
      type:
        type: Article
    permalink:
      path: '/:title/'
  - filter:
      type:
        type: WebPage
    permalink:
      path: '/:title/'
      navigable: true
purpose:
  - name: follow
    url: null
    item: 3646ec0f-28ea-4d62-937f-fe4eb0146eb7
